name: iris_classification
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip=23.3.1
  - pip:
    - mlflow==2.19.0
    - scikit-learn==1.6.1
    - pandas==2.1.1
    - numpy==1.24.3
    - matplotlib==3.7.2
    - seaborn==0.12.2
    - plotly==5.15.0
    - scipy==1.11.1
    - joblib==1.3.2
    - click==8.1.7